version: '3'

services:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '80:80'
#    depends_on:
#      - pgsql
#      - redis
#    networks:
#      - backend

  pgsql:
    image: 'postgres:13'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-shorty}'
      POSTGRES_USER: '${DB_USERNAME:-shorty}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-shorty}", "-U", "${DB_USERNAME:-shorty}"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

networks:
  backend:

volumes:
  pgsql:
    driver: local
  redis:
    driver: local